# Generated by Django 5.1.2 on 2024-10-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes_images/'),
        ),
        migrations.AddField(
            model_name='notes',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Below Normal'), (3, 'Normal'), (4, 'Above Normal'), (5, 'High')], default=3),
        ),
    ]
